# Generated by Django 5.2.8 on 2025-12-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Начало')),
                ('end', models.DateTimeField(verbose_name='Конец')),
                ('status', models.CharField(default='Создана', max_length=10, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Инфо',
                'verbose_name_plural': 'Инфо',
                'db_table': 'Mailing',
                'ordering': ['status', 'start'],
                'permissions': [('can_disable_mailing', 'Может отключать рассылку'), ('can_view_all_mailings', 'Может просматривать все рассылки')],
            },
        ),
        migrations.CreateModel(
            name='MailingIsSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mailing', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10, verbose_name='Успешно/Не успешно')),
                ('answer', models.CharField(max_length=500, verbose_name='Ответ почтового сервера')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
                'db_table': 'MailingIsSuccess',
                'ordering': ['date_mailing'],
            },
        ),
        migrations.CreateModel(
            name='MailingRecipients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='email')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ф.И.О.')),
                ('comment', models.TextField(verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Получатель',
                'verbose_name_plural': 'Получатели',
                'db_table': 'MailingRecipients',
                'ordering': ['email'],
                'permissions': [('can_manage_recipients', 'Может управлять всеми получателями')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Тема')),
                ('body', models.TextField(verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Текст',
                'db_table': 'Message',
                'ordering': ['header'],
                'permissions': [('can_manage_messages', 'Может управлять всеми сообщениями')],
            },
        ),
    ]
